package promhs;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
/**
 *
 * @author I Ketut Agus Restu Wijaya 20103347
 */
public class frdsn extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;
    dbKoneksi cnn = new dbKoneksi();
    loadIMG img = new loadIMG();
    /**
     * Creates new form frdsn
     */
    public frdsn() {
        initComponents();
        this.initTable();
        this.getdata();
        this.cdmbatal.setVisible(false);
    }
    private void getdata(){
        String sql = "Select NIDN, NAMA, JK, GELAR FROM ds;";
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    try{
        this.tampildata(sql);
        while(this.rs.next()){
            Object[] obj = new Object[4];
            obj[0]= this.rs.getString("NIDN");
            obj[1]= this.rs.getString("NAMA");
            String txJK = this.rs.getString("JK");
            if(txJK.equals("L")){
                obj[2]="Laki-Laki";
            }else{
                obj[2]="Perempuan";
            }
            obj[3]= this.rs.getString("GELAR");
        model.addRow(obj);
        }
    }catch(Exception e){
    }
    }
    private boolean UpdateData(String SQL){
        boolean hsl = false;
        try{
            Statement stmt= cnn.koneksi().createStatement();
            stmt.executeUpdate(SQL);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi masalah pada intruksi SQL");
        }
        return hsl;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cdmtambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        txNIDN = new javax.swing.JTextField();
        imgphoto = new javax.swing.JLabel();
        lbCRUDds = new javax.swing.JLabel();
        txDS = new javax.swing.JTextField();
        txGL = new javax.swing.JTextField();
        txJKL = new javax.swing.JRadioButton();
        txJKP = new javax.swing.JRadioButton();
        cdmsimpan = new javax.swing.JButton();
        cdmubah = new javax.swing.JButton();
        cdmhapus = new javax.swing.JButton();
        cdmbatal = new javax.swing.JButton();
        cdmtutup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("List Data Dosen");

        cdmtambah.setText("Tambah Data");
        cdmtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmtambahActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        txNIDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIDNActionPerformed(evt);
            }
        });

        lbCRUDds.setText("Detail");

        buttonGroup1.add(txJKL);
        txJKL.setText("Laki-Laki");

        buttonGroup1.add(txJKP);
        txJKP.setText("Perempuan");

        cdmsimpan.setText("simpan");
        cdmsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmsimpanActionPerformed(evt);
            }
        });

        cdmubah.setText("Update");
        cdmubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmubahActionPerformed(evt);
            }
        });

        cdmhapus.setText("Hapus");
        cdmhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmhapusActionPerformed(evt);
            }
        });

        cdmbatal.setText("Batal");
        cdmbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmbatalActionPerformed(evt);
            }
        });

        cdmtutup.setText("Tutup form");
        cdmtutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmtutupActionPerformed(evt);
            }
        });

        jLabel2.setText("NIDN");

        jLabel3.setText("NAMA");

        jLabel4.setText("JENIS KELAMIN");

        jLabel5.setText("GELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cdmtambah))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(imgphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(304, 304, 304)
                                        .addComponent(cdmbatal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(154, 154, 154)
                                        .addComponent(jLabel5)
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cdmtutup))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txGL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txJKL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txJKP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txDS, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cdmsimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cdmubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cdmhapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbCRUDds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdmtambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCRUDds)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txJKL)
                            .addComponent(txJKP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(imgphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdmsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cdmubah)
                    .addComponent(cdmhapus)
                    .addComponent(cdmbatal)
                    .addComponent(cdmtutup))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdmtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmtambahActionPerformed
        this.cdmtambah.setEnabled(false);
        this.cdmubah.setEnabled(false);
        this.cdmhapus.setEnabled(false);
        this.cdmbatal.setEnabled(true);
        this.cdmsimpan.setEnabled(true);
        this.cdmtutup.setVisible(true);
        
        this.txDS.setText("");
        this.txNIDN.setText("");
        this.txGL.setText("");
        
        this.lbCRUDds.setText("Tambah Data Dosen");
    }//GEN-LAST:event_cdmtambahActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        String urlGambarNull = "src/img/gambar.jpg";
        this.txNIDN.setText(model.getValueAt(tb.getSelectedRow(),0).toString());
        this.txDS.setText(model.getValueAt(tb.getSelectedRow(),1).toString());
        String txJK = model.getValueAt(tb.getSelectedRow(),2).toString();
        if(txJK.equals("Perempuan")){
            this.txJKP.setSelected(true);
        }else{
            this.txJKP.setSelected(true);
        }
        this.txGL.setText(model.getValueAt(tb.getSelectedRow(),3).toString());
        String urlGambar = "src/img/"+this.txNIDN.getText()+".jpg";
        BufferedImage loadImg = img.loadImage(urlGambar);
        if(loadImg == null ){
            loadImg = img.loadImage(urlGambarNull);
        }
        ImageIcon imageIcon = new ImageIcon(loadImg);
        this.imgphoto.setIcon(imageIcon);

        this.lbCRUDds.setText("Edit Data"+this.txNIDN.getText());
        this.cdmsimpan.setEnabled(false);
        this.cdmubah.setEnabled(true);
        this.cdmhapus.setEnabled(true);
    }//GEN-LAST:event_tbMouseClicked

    private void txNIDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIDNActionPerformed

    private void cdmsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmsimpanActionPerformed
        String NIDN = this.txNIDN.getText();
        String NAMA = this.txDS.getText();
        String JNS_K = "L";
       if(this.txJKP.isSelected()){
           JNS_K="P";
       }
        String GELAR = this.txGL.getText();
        String SQLInsert = "INSERT INTO ds (NIDN, NAMA, JK, GELAR) VALUES('"+NIDN+"','"+NAMA+"','"+JNS_K+"','"+GELAR+"');";
        if(this.UpdateData(SQLInsert)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data Ditambahkan");
        }
        this.cdmtambah.setEnabled(false);
        this.cdmbatal.setVisible(false);
        this.cdmtutup.setEnabled(true);
        this.cdmtambah.setEnabled(true);
    }//GEN-LAST:event_cdmsimpanActionPerformed

    private void cdmubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmubahActionPerformed
        String NIDN = this.txNIDN.getText();
        String NAMA = this.txDS.getText();
        String JNS_K = "L";
        if(this.txJKP.isSelected()){
            JNS_K="P";
        }
        String GELAR = this.txGL.getText();
        String SQLUpdate = "UPDATE ds SET NAMA='"+NAMA+"',JK='"+JNS_K+"',GELAR='"+GELAR+"'WHERE NIDN='"+NIDN+"';";
        if(this.UpdateData(SQLUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data Terupdate");
        }
    }//GEN-LAST:event_cdmubahActionPerformed

    private void cdmhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmhapusActionPerformed
        String NIDN = this.txNIDN.getText();
        String NAMA = this.txDS.getText();

        int opsi = JOptionPane.showConfirmDialog(null, "Yakin akan menghapus data "+NAMA+"("+NIDN+")?","Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(opsi == JOptionPane.YES_OPTION){
            String SQLDelete = "DELETE FROM ds WHERE NIDN='"+NIDN+"';";
            if(this.UpdateData(SQLDelete)){
                this.getdata();
                JOptionPane.showMessageDialog(null, "Data Terhapus");
            }
        }
    }//GEN-LAST:event_cdmhapusActionPerformed

    private void cdmbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmbatalActionPerformed
        this.cdmtutup.setEnabled(true);
        this.cdmtambah.setEnabled(true);
        this.cdmtambah.setEnabled(false);
        this.cdmbatal.setEnabled(true);
    }//GEN-LAST:event_cdmbatalActionPerformed

    private void cdmtutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmtutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_cdmtutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frdsn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cdmbatal;
    private javax.swing.JButton cdmhapus;
    private javax.swing.JButton cdmsimpan;
    private javax.swing.JButton cdmtambah;
    private javax.swing.JButton cdmtutup;
    private javax.swing.JButton cdmubah;
    private javax.swing.JLabel imgphoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCRUDds;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txDS;
    private javax.swing.JTextField txGL;
    private javax.swing.JRadioButton txJKL;
    private javax.swing.JRadioButton txJKP;
    private javax.swing.JTextField txNIDN;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        model = new DefaultTableModel();
        tb.setModel(model);
        model.addColumn("NIDN");
        model.addColumn("NAMA");
        model.addColumn("JENIS KELAMIN");
        model.addColumn("GELAR");
        
    }
    private void tampildata(String sql){
        try{
            Statement stmt = cnn.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("kendala pada query");
        }
    }
}
