package promhs;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
/**
 *
 * @author Restu Wijaya
 */
public class frmdsn extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;
    dbKoneksi cnn = new dbKoneksi();
    loadIMG img = new loadIMG();
    
    
private boolean UpdateData(String SQL){
    boolean hsl = false;
    try{
        Statement stmt = cnn.koneksi().createStatement();
        stmt.executeUpdate(SQL);
        hsl = true;
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Terjai kendala pada Intruksi SQL");
    }
    return hsl;
}
    /**
     * Creates new form frmdsn
     */
    public frmdsn() {
        initComponents();
        this.initTable();
        this.getdata();
        this.cdmbatal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cdmtambah = new javax.swing.JButton();
        cdmsimpan = new javax.swing.JButton();
        cdmubah = new javax.swing.JButton();
        cdmhapus = new javax.swing.JButton();
        cdmbatal = new javax.swing.JButton();
        cdmtutup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNIDN = new javax.swing.JTextField();
        txDS = new javax.swing.JTextField();
        txGL = new javax.swing.JTextField();
        imgphoto = new javax.swing.JLabel();
        lbCRUDds = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        jLabel1.setText("List Data Dosen");

        cdmtambah.setText("Tambah Data");
        cdmtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmtambahActionPerformed(evt);
            }
        });

        cdmsimpan.setText("simpan");
        cdmsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmsimpanActionPerformed(evt);
            }
        });

        cdmubah.setText("Update");
        cdmubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmubahActionPerformed(evt);
            }
        });

        cdmhapus.setText("Hapus");
        cdmhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmhapusActionPerformed(evt);
            }
        });

        cdmbatal.setText("Batal");
        cdmbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmbatalActionPerformed(evt);
            }
        });

        cdmtutup.setText("Tutup form");
        cdmtutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmtutupActionPerformed(evt);
            }
        });

        jLabel2.setText("NIDN");

        jLabel3.setText("Nama Dosen");

        jLabel4.setText("Gelar");

        txNIDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIDNActionPerformed(evt);
            }
        });

        lbCRUDds.setText("Detail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cdmsimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdmubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cdmhapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cdmbatal)
                .addGap(18, 18, 18)
                .addComponent(cdmtutup)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cdmtambah)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(imgphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(txDS, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txGL)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbCRUDds, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cdmtambah))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbCRUDds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgphoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdmsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cdmubah)
                        .addComponent(cdmhapus)
                        .addComponent(cdmbatal)
                        .addComponent(cdmtutup)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdmtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmtambahActionPerformed
        this.cdmtambah.setEnabled(false);
        this.cdmubah.setEnabled(false);
        this.cdmhapus.setEnabled(false);
        this.cdmbatal.setEnabled(true);
        this.cdmsimpan.setEnabled(true);
        this.cdmtutup.setVisible(true);
    }//GEN-LAST:event_cdmtambahActionPerformed

    private void cdmsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmsimpanActionPerformed
       String NIDN = this.txNIDN.getText();
       String NAMA = this.txDS.getText();
       String GELAR = this.txGL.getText();
       
       String SQLInsert = "INSERT INTO dsn(NIDN,Nama,Gelar) VALUES('"+NIDN+"','"+NAMA+"','"+GELAR+"');";
       if(this.UpdateData(SQLInsert)){
           this.getdata();
           JOptionPane.showMessageDialog(null, "Data Ditambahkan");
       }
       this.cdmtambah.setEnabled(false);
       this.cdmbatal.setVisible(false);
       this.cdmtutup.setEnabled(true);
       this.cdmtambah.setEnabled(true);
    }//GEN-LAST:event_cdmsimpanActionPerformed

    private void txNIDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIDNActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
      String urlGambarNull = "src/img/gambar.jpg";
      this.txNIDN.setText(model.getValueAt(tb.getSelectedRow(),0).toString());
      this.txDS.setText(model.getValueAt(tb.getSelectedRow(),1).toString());
      this.txGL.setText(model.getValueAt(tb.getSelectedRow(),2).toString());
      String urlGambar = "src/img/"+this.txNIDN.getText()+".jpg";
      BufferedImage loadImg = img.loadImage(urlGambar);
      if(loadImg == null ){
          loadImg = img.loadImage(urlGambarNull);
      }
      ImageIcon imageIcon = new ImageIcon(loadImg);
      this.imgphoto.setIcon(imageIcon);
      
      this.lbCRUDds.setText("Edit Data"+this.txNIDN.getText());
      this.cdmsimpan.setEnabled(false);
      this.cdmubah.setEnabled(true);
      this.cdmhapus.setEnabled(true);
    }//GEN-LAST:event_tbMouseClicked

    private void cdmubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmubahActionPerformed
        String NIDN = this.txNIDN.getText();
        String NAMA = this.txDS.getText();
        String GELAR = this.txGL.getText();
        
        String SQLUpdate = "UPDATE dsn SET Nama='"+NAMA+"',Gelar='"+GELAR+"'WHERE NIDN='"+NIDN+"';";
        if(this.UpdateData(SQLUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data Terupdate");
        }
    }//GEN-LAST:event_cdmubahActionPerformed

    private void cdmhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmhapusActionPerformed
        String NIDN = this.txNIDN.getText();
        String NAMA = this.txDS.getText();
        
        int opsi = JOptionPane.showConfirmDialog(null, "Yakin akan menghapus data "+NAMA+"("+NIDN+")?","Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(opsi == JOptionPane.YES_OPTION){
        String SQLDelete = "DELETE FROM dsn WHERE NIDN='"+NIDN+"';";
        if(this.UpdateData(SQLDelete)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data Terhapus");
        }
    }
    }//GEN-LAST:event_cdmhapusActionPerformed

    private void cdmbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmbatalActionPerformed
       this.cdmtutup.setEnabled(true);
       this.cdmtambah.setEnabled(true);
       this.cdmtambah.setEnabled(false);
       this.cdmbatal.setEnabled(true);
    }//GEN-LAST:event_cdmbatalActionPerformed

    private void cdmtutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmtutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_cdmtutupActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmdsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmdsn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdmbatal;
    private javax.swing.JButton cdmhapus;
    private javax.swing.JButton cdmsimpan;
    private javax.swing.JButton cdmtambah;
    private javax.swing.JButton cdmtutup;
    private javax.swing.JButton cdmubah;
    private javax.swing.JLabel imgphoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCRUDds;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txDS;
    private javax.swing.JTextField txGL;
    private javax.swing.JTextField txNIDN;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        model = new DefaultTableModel();
        tb.setModel(model);
        model.addColumn("NIDN");
        model.addColumn("Nama");
        model.addColumn("Gelar");
    }
    private void tampildata(String sql){
        try{
            Statement stmt = cnn.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("Terjadi masalah pada query");
        }
    }

    private void getdata() {
      String sql = "Select NIDN, Nama, Gelar FROM dsn;";
      model.getDataVector().removeAllElements();
      model.fireTableDataChanged();
    try{
        this.tampildata(sql);
        while(this.rs.next()){
            Object[] obj =new Object[3];
            obj[0] = this.rs.getString("NIDN");
            obj[1] = this.rs.getString("Nama");
            obj[2] = this.rs.getString("Gelar");
            
            model.addRow(obj);
        }
    }catch(Exception e){
    }
    }
}
